services:
  platform-db:
    image: postgres:14
    restart: always
    container_name: platform-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: platform
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
